### ISSUE TITLE
Can't see Contact form labels in dark mode

### ISSUE THREAD

**Issue by charles-hood** [stackrole/gatsby-starter-foundation#16]
![2020-12-21](https://user-images.githubusercontent.com/16855550/102855563-de8f1e00-43f2-11eb-819d-2dc47fdc6a54.png)

Recommend changing /src/assets/scss/style.scss line 317, to color: #777

This grey color shows up nicely on both light or dark backgrounds.

**Comment by sksameer204** [comment]
Thank you for the suggestion we just fixed it. cheers

![image](https://user-images.githubusercontent.com/41252589/102863164-3449e180-4458-11eb-9171-036ec7d4ac30.png)
