### ISSUE TITLE
Search integration

### ISSUE THREAD

**Issue by sid-r-singh** [stackrole/gatsby-starter-foundation#23]
Feature request : search integration.
Before anything else, I must tell you that this is the best 🥇  ever blogging theme I came across among all the gatsby stater themes. You guys deserve a big applause 👏  especially for making it a very mobile friendly as well 🥳 . I just wanted to make a feature request. Now a days every blogging site has a search facility. Particularly in this blog, I think it (search) will fit rightly in the hamburger menu (in the mobile edition). With that in place I think this blog will be unmatched in terms of features, design & performance/speed to any other Jam-stack blog. Kudos to you again.

**Comment by munwr** [comment]
Thank you for your kind words, We will plan accordingly and integrate search into this. :)

If you are looking for a premium feature-packed jamstack template that bundles with search and other amazing features. Do check out **Maestro** - https://stackrole.com/jamstack/maestro

**Comment by munwr** [comment]
Just launched search and option change primary color
