### ISSUE TITLE
Can't see the blog post date in dark mode

### ISSUE THREAD

**Issue by TheRuchirShah** [stackrole/gatsby-starter-foundation#25]
In the normal (light) mode the date is visible, but in the dark mode, the date is not visible.
\
&nbsp;
![git issue](https://user-images.githubusercontent.com/39954164/117237284-3c734e00-ae48-11eb-9351-97e826bedeb9.png)
![git issue 2](https://user-images.githubusercontent.com/39954164/117237294-42692f00-ae48-11eb-881e-4542b1e33714.png)

**Comment by munwr** [comment]
Thank for reporting this. We will it fix :)
