### ISSUE TITLE
Feature Request - Tags

### ISSUE THREAD

**Issue by TheRuchirShah** [stackrole/gatsby-starter-foundation#32]
Now all blog sites attribute a must essential on their post is tags. It becomes easy to find similar blog posts by the tags attached to them.

**Comment by donaldboulton** [comment]
Added tags to my fork at [Bibwoe.com Repo](https://github.com/donaldboulton/bibwoe.com)

Add tags to node and a tag page and tag template then look at how I added it to  the Layout component line 84, then line 118

**Comment by munwr** [comment]
Please create a pull request, make sure you pull all our latest commits then create a pull request
