### ISSUE TITLE
Search fixed

### ISSUE THREAD

**Issue by donaldboulton** [stackrole/gatsby-starter-foundation#33]
I usually use Algolia search but I thought I would try lunar and found  several errors in you code.

First in Gatsby config you have @gatsby-contrib/gatsby-plugin-elasticlunr-search listed under remark components move it to right above gatsby-plugin-sass, and configure it as in my repo listed below.

Then go to my repo and view my search component = complete rebuild at [Bibwoe.com Repo](https://github.com/donaldboulton/bibwoe.com)

Lost of other tidbits of stuff included like tags, timeToRead ect. you might want to look at.

Happy Coding
Donald Boulton

**Comment by munwr** [comment]
The search is already working, Check once using the latest commits. Please revert back to us as needed, if you fixing something please create a pull request
