### ISSUE TITLE
serializer for mini-css-extract-plugin/dist/CssModule/null is already registered after running gatsby develop 

### ISSUE THREAD

**Issue by mwmwaxxeromwmw** [stackrole/gatsby-starter-foundation#35]
So I cloned the repository via github first, to develop locally but when I did npm install and then gatsby develop, then after receiving the error below, I also did "gatsby new gatsby-starter-foundation https://github.com/stackrole/gatsby-starter-foundationin" but still in the end I ALWAYS receive the following ERROR

ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

  Error: ObjectMiddleware.register: serializer for mini-css-extract-plugin/dist/CssModule/null is already registered

  - ObjectMiddleware.js:193 Object.register
    [moksgatsby]/[webpack]/lib/serialization/ObjectMiddleware.js:193:10

  - index.js:182 Function.getCssModule
    [moksgatsby]/[mini-css-extract-plugin]/dist/index.js:182:34

  - index.js:389 MiniCssExtractPlugin.apply
    [moksgatsby]/[mini-css-extract-plugin]/dist/index.js:389:44

  - webpack.js:73 createCompiler
    [moksgatsby]/[webpack]/lib/webpack.js:73:12

  - webpack.js:134 create
    [moksgatsby]/[webpack]/lib/webpack.js:134:16

  - webpack.js:158 webpack
    [moksgatsby]/[webpack]/lib/webpack.js:158:32

  - index.js:58 f
    [moksgatsby]/[webpack]/lib/index.js:58:16

  - start-server.ts:173 startServer
    [moksgatsby]/[gatsby]/src/utils/start-server.ts:173:20

  - task_queues.js:60 runNextTicks
    internal/process/task_queues.js:60:5

  - timers.js:437 processImmediate
    internal/timers.js:437:9

  - start-webpack-server.ts:44 startWebpackServer
    [moksgatsby]/[gatsby]/src/services/start-webpack-server.ts:44:7

not finished Building development bundle - 9.213s
not finished Caching HTML renderer compilation - 4.567s

**Comment by munwr** [comment]
We have fixed most of these issues, please pull our latest commits. Thank you for using Stackrole
