### ISSUE TITLE
Match Netlify.Toml file to current Node version used by Foundation

### ISSUE THREAD

**Issue by TimothyBlajsa** [stackrole/gatsby-starter-foundation#43]
When forking the latest commit of the gastby starter foundation, the Node version represented in the Netlify.Toml file does not match the current Node version represented in the .node-version file found in the root.

This is a simple update and I would like to be assigned this issue to resolve.

**Comment by TimothyBlajsa** [comment]
I would like to be assigned this issue please.

**Comment by munwr** [comment]
Sure, @TimothyBlajsa
