### ISSUE TITLE
Gatsby Plugin Netlify Cache Deprecated

### ISSUE THREAD

**Issue by TimothyBlajsa** [stackrole/gatsby-starter-foundation#44]
The gastby-plugin-netlify-cache that is listed in the netlify.toml is no longer supported and is deprecated.

This plugin has since been replaced with a new plugin called netlify-plugin-gatsby, having the user change the netlify.toml to use the new plugin, installing it, and then adding it to the Gatsby-config.js file. 

Gastby-plugin-netlify is installed as a dev dependency. 

[Gastby Plugin Update](https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cache/)

**Comment by munwr** [comment]
Sure, please create a pull request
