### ISSUE TITLE
Pagination bug: blog-list template pagination counts all markdown pages instead only blog-post ones.

### ISSUE THREAD

**Issue by t-fan-slavik** [stackrole/gatsby-starter-foundation#6]
To reproduce an issue:

In the gatsby-node.js change the "postsPerPage" to a smaller value, e.g. 4.
Then after rebuild go to the blog-list page (/blog) and you'll see that the last page in pagination is empty.

**Comment by stackrole-dev** [comment]
Thank you @t-fan-slavik, we have merged your pull request 👍
