### ISSUE TITLE
The mobile version defaults to dark mode. Can this be prevented?

### ISSUE THREAD

**Issue by PatMulvihill** [stackrole/gatsby-starter-foundation#62]
When navigating to the demo website on mobile, the pages render in dark mode by default. Is this preventable so that there is a uniform experience across mobile and desktop devices?

**Comment by munwr** [comment]
If you are using dark mode as default setting in your mobile, then it would
switch automatically

**Comment by PatMulvihill** [comment]
I see - thank you! I disabled default this default behavior in my own fork by removing the dark "mode" in src/gatsby-plugin-theme-ui/index.js.
