### ISSUE TITLE
Error: Command failed with exit code 1: npm install

### ISSUE THREAD

**Issue by K2adir** [stackrole/gatsby-starter-foundation#69]
running this -->
`gatsby new gatsby-starter-foundation https://github.com/stackrole/gatsby-starter-foundation`

results this

`
Error: Command failed with exit code 1: npm install

  - error.js:60 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:60:11

  - index.js:118 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:118:26

  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5

  - init-starter.js:135 install
    [lib]/[gatsby-cli]/lib/init-starter.js:135:7

  - init-starter.js:202 clone
    [lib]/[gatsby-cli]/lib/init-starter.js:202:3

  - init-starter.js:343 initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:343:5

  - create-cli.js:458
    [lib]/[gatsby-cli]/lib/create-cli.js:458:9
`

**Comment by munwr** [comment]
In the latest commit fixed build issues, please make sure you have Node >=18
